import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[env]
WINIT_X11_SCALE_FACTOR = "1.1"

[font]
size = 13.0

[font.normal]
family = "Inconsolata"
style = "Mono"

[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
]
